---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tonetag-cert
spec:
  secretName: tonetag-cert
  commonName: tonetag.is
  dnsNames:
    - "tonetag.is"
    - "*.tonetag.is"
  issuerRef:
    name: tonetag-issuer
    kind: Issuer
    group: cert-manager.io
...