helmCharts:
- name: tonetag
  releaseName: tonetag
  version: "2.0.0"
  repo: https://tonetag.github.io/charts
  includeCRDs: false
  valuesInline:
    replicaCount: 5
    
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        nginx.ingress.kubernetes.io/force-ssl-redirect: "false"  # Cloudflare handles this
        nginx.ingress.kubernetes.io/ssl-redirect: "false"  # Cloudflare handles this
      hosts:
        - host: "tonetag.is"
          paths:
            - path: /
              pathType: Prefix
        - host: "dev.tonetag.is"
          paths:
            - path: /
              pathType: Prefix
      tls:
      - secretName: tonetag-cert
        hosts:
          - "tonetag.is"
          - "dev.tonetag.is"

generators:
  - ./kustomize-secret-generator.yaml

resources:
  - ./cert-tonetag.yaml
  - ./issuer-tonetag.yaml
